### ISSUE TITLE
Not able to find how to create redirectURI

### ISSUE THREAD

**Issue by sanket-t-shah** [GSingh01/ad-b2c-react-native#11] opened 2020-04-05 16:11 UTC
How to create redirectURI for react-native app built via Expo that is common to both iOS and Android?

**Comment by GSingh01** [comment] 2020-04-05 21:31
Thanks for your query.

The redirect URI required for Login is not your app's redirect uri used by native code to reopen the app.

Create any global unique identifier to provide it in Azure AD portal configs and use the same in Login component. This redirect URI should be separate from your regular app's redirect URI otherwise it might create problems.

**Comment by sanket-t-shah** [comment] 2020-04-06 08:49
Can you please give an example of the same as am not able to follow your response? Here is what I've right now.

```
const ApplicationConstants = {
    AzureAppId: '323b3801-8bb9-4e66-832b-920377bbef62',
    AzureRedirectURI: 'msal323b3801-8bb9-4e66-832b-920377bbef62://auth',
    AzureTenant: 'reactnativeapp',
    AzureLoginPolicy: 'b2c_1_signupin',
    AzurePasswordResetPolicy: 'b2c_1_passreset',
    AzureProfileEditPolicy: 'b2c_1_editprof',
};

export { ApplicationConstants };
```

```
import React, { useContext } from 'react';
import { NavigationEvents } from 'react-navigation';
import { View, Button, StyleSheet } from 'react-native';
import { Context as AuthContext } from '../context/AuthContext';
import { LoginView } from 'ad-b2c-react-native';
import * as SecureStore from 'expo-secure-store';
import { ApplicationConstants } from '../constants';
import Spinner from '../components/Spinner';

const SigninScreen = () => {
    const { signin, handleErrorMessage, clearErrorMessage } = useContext(AuthContext);

    return (
        <View
            style={styles.container}>
            <NavigationEvents
                onWillBlur={clearErrorMessage} />
            <LoginView
                appId={ApplicationConstants.AzureAppId}
                redirectURI={ApplicationConstants.AzureRedirectURI}
                tenant={ApplicationConstants.AzureTenant}
                loginPolicy={ApplicationConstants.AzureLoginPolicy}
                passwordResetPolicy={ApplicationConstants.AzurePasswordResetPolicy}
                profileEditPolicy={ApplicationConstants.AzureProfileEditPolicy}
                onSuccess={signin}
                onFail={handleErrorMessage}
                secureStore={SecureStore}
                renderLoading={() => {
                    return (<Spinner />);
                }}
            />
        </View>
    );
};

SigninScreen.navigationOptions = () => {
    return {
        headerShown: false
    };
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center"
    }
});

export default SigninScreen;

```

```
import { AsyncStorage } from 'react-native';
import createDataContext from './createDataContext';
import trackerApi from "../api/tracker";
import { navigate } from '../navigationRef';

const authReducer = (state, action) => {
    switch (action.type) {
        case 'add_error':
            return { ...state, errorMessage: action.payload };
        case 'signup':
            return { ...state, token: action.payload };
        case 'signin':
            return { ...state, token: action.payload };
        case 'set_error_message':
            return { ...state, errorMessage: action.payload };
        case 'clear_error_message':
            return { ...state, errorMessage: '' };
        case 'signout':
            return { token: null, errorMessage: '' };
        default:
            return state;
    }
};

const handleErrorMessage = dispatch => () => {
    console.log('Error');
    dispatch({ type: 'set_error_message', payload: 'An error has occurred. Error Message:' });
};

const tryLocalSignin = dispatch => async () => {
    const token = await AsyncStorage.getItem('token');

    if (token) {
        dispatch({ type: 'signin', payload: token });
        navigate('TrackList');
    }
    else {
        navigate('Signin');
    }
};

const clearErrorMessage = dispatch => () => {
    dispatch({ type: 'clear_error_message' });
};

const signup = (dispatch) => async ({ email, password }) => {
    try {
        const response = await trackerApi.post('/signup', { email, password });
        await AsyncStorage.setItem('token', response.data.token);
        dispatch({ type: 'signup', payload: response.data.token });

        navigate('TrackList');
    } catch (error) {
        dispatch({
            type: 'add_error',
            payload: 'Something went wrong with Sign up. '
        });
    }
};


const signin = (dispatch) => async () => {
    try {
        console.log("Hi");
        const response = await trackerApi.post('/signin', { email, password });
        await AsyncStorage.setItem('token', response.data.token);
        dispatch({ type: 'signin', payload: response.data.token });

        navigate('TrackList');
    } catch (error) {
        dispatch({
            type: 'add_error',
            payload: 'Something went wrong with Sign in. '
        });
    }
};

const signout = (dispatch) => async () => {
    await AsyncStorage.removeItem('token');
    dispatch({ type: 'signout' });
    navigate('loginFlow');
};

export const { Provider, Context } = createDataContext(
    authReducer,
    {
        signin,
        signout,
        signup,
        handleErrorMessage,
        clearErrorMessage,
        tryLocalSignin
    },
    {
        token: null,
        errorMessage: ''
    });
```

**Comment by GSingh01** [comment] 2020-04-10 05:39
@sanket-t-shah if the issue is solved please close it

**Closed** 2020-04-16 00:13 UTC
Labels: question
